### ISSUE TITLE
yolov7 P6模型训练

### ISSUE THREAD

**Issue by miracletrespasser** [we0091234/yolov7_plate#15]

**Comment by miracletrespasser** [comment]
您好，想问一下目前可以支持1280 P6的大模型训练吗？尝试去替换了models文件里的设置，结果不是很理想

**Comment by we0091234** [comment]
> 您好，想问一下目前可以支持1280 P6的大模型训练吗？尝试去替换了models文件里的设置，结果不是很理想

哦，没试过呢，我这是车牌任务比较简单，没试过那么大的
