### ISSUE TITLE
labelling

### ISSUE THREAD

**Issue by fachdf** [we0091234/yolov7_plate#4]
嗨，很抱歉我问这个问题，我不是来自中国，但我对你为我的大学研究所做的工作很感兴趣。 您使用什么工具来标记图像？ labelimg 似乎没有提供标记 4 个关键点的方法。 对不起中文不好，我用谷歌翻译

**Comment by we0091234** [comment]
> 嗨，很抱歉我问这个问题，我不是来自中国，但我对你为我的大学研究所做的工作很感兴趣。 您使用什么工具来标记图像？ labelimg 似乎没有提供标记 4 个关键点的方法。 对不起中文不好，我用谷歌翻译

use labelme

**Comment by fachdf** [comment]
> > 嗨，很抱歉我问这个问题，我不是来自中国，但我对你为我的大学研究所做的工作很感兴趣。 您使用什么工具来标记图像？ labelimg 似乎没有提供标记 4 个关键点的方法。 对不起中文不好，我用谷歌翻译
> 
> use labelme

What software do you use to convert the labelme JSON format to yolo TXT format?

**Comment by we0091234** [comment]
> > > 嗨，很抱歉我问这个问题，我不是来自中国，但我对你为我的大学研究所做的工作很感兴趣。 您使用什么工具来标记图像？ labelimg 似乎没有提供标记 4 个关键点的方法。 对不起中文不好，我用谷歌翻译
> > 
> > 
> > use labelme
> 
> What software do you use to convert the labelme JSON format to yolo TXT format?

in this project  https://github.com/we0091234/Chinese_license_plate_detection_recognition  
![image](https://user-images.githubusercontent.com/29919617/221789701-b4367b6e-ea21-41dd-ae8b-b0f45e15c819.png)

**Comment by fachdf** [comment]
> > > > 嗨，很抱歉我问这个问题，我不是来自中国，但我对你为我的大学研究所做的工作很感兴趣。 您使用什么工具来标记图像？ labelimg 似乎没有提供标记 4 个关键点的方法。 对不起中文不好，我用谷歌翻译
> > > 
> > > 
> > > use labelme
> > 
> > 
> > What software do you use to convert the labelme JSON format to yolo TXT format?
> 
> in this project https://github.com/we0091234/Chinese_license_plate_detection_recognition ![image](https://user-images.githubusercontent.com/29919617/221789701-b4367b6e-ea21-41dd-ae8b-b0f45e15c819.png)

thank you
